### ISSUE TITLE
Help with running wireguard

### ISSUE THREAD

**Issue by lpzrulez** [gpopesc/wireguard-module-synology#5]
I followed the steps for my synology nas ds923+
but when I run sudo wg-quick up command it says command not found 
Also sudo wg command doesn’t run 
I installed the geminilake and it installed successfully 
Please help

**Comment by gpopesc** [comment]
With this project you install only binaries for synology in order to work wireguard.
Further you need to install in docker additional application in order to make it work.
I recommend you to install  this : [https://github.com/WeeJeWel/wg-easy](https://github.com/WeeJeWel/wg-easy).  The  command you mentioned will work in the container wg-easy, but it is better to use the interface of it.

**Comment by lpzrulez** [comment]
Thank you so very much
